---
volumes:
  matter_server_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/matter-server/"

services:
  matter-server:
    image: ghcr.io/matter-js/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    # Required for mDNS to work correctly
    network_mode: host
    security_opt:
      # Needed for Bluetooth via D-Bus
      - apparmor:unconfined
    volumes:
      - matter_server_data:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    labels:
      - homepage.group=Home Automation
      - homepage.name=Matter Server
      - homepage.icon=mdi-chip
      - homepage.description=Python Matter Server
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"
