version: '3.4'

volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/influxdb_data/"

services:
  home-assistant:
    image: homeassistant/home-assistant:latest
    container_name: home-assistant
    depends_on:
      - deconz
      - eclipse-mosquitto
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
      - "traefik.backend=home-assistant"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix: /hass"
      - "traefik.port=8123"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:8123"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    network_mode: "host"
    environment:
      - PUID=200
      - PGID=200
    devices:
      # - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1WRPEJT-if00-port0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/zwave
    ports:
      - 80:8300
      - 8123:8123
      - 8300:8300
    volumes:
      - /docker/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  esphome:
    image: esphome/esphome:latest
    container_name: esphome
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:6052"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/home-assistant/config/esphome:/config
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  deconz:
    image: marthoc/deconz:latest
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:8100/pwa/login.html"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8100:8100
      - 8143:8143
      - 1900:1900
      - 5900:5900
    volumes:
      - /docker/deCONZ/config:/root/.local/share/dresden-elektronik/deCONZ
      - /docker/deCONZ/otau:/root/otau/
    devices:
      - /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DO00KFKX-if00-port0:/dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8100
      - DECONZ_WS_PORT=8143
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=1
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=${DECONZ_VNC_PASSWORD}
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  eclipse-mosquitto:
    image: eclipse-mosquitto:latest
    container_name: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
        - /docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - /docker/mosquitto/data:/mosquitto/data
        - /docker/mosquitto/log:/mosquitto/log
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  nodered:
    restart: unless-stopped
    image: nodered/node-red-docker:latest
    container_name: node-red
    ports:
      - 1880:1880
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:1880"]
      start_period: 60s 
      interval: 30s 
      timeout: 10s 
      retries: 5
    environment:
      TZ: Europe/London
    volumes:
      - /docker/node-red/data:/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefixStrip: /grafana/"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:3000/api/health"]
      test: ["CMD", "wget", "--spider", "-tries=1", "--quiet", "http://homeauto.vpn.glasgownet.com:3000/api/health"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      # http://docs.grafana.org/installation/configuration/#using-environment-variables
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,vonage-status-panel,grafana-influxdb-08-datasource,ryantxu-ajax-panel,raintank-worldping-app
      - GF_SERVER_ROOT_URL=http://homeauto.vpn.glasgownet.com
      - GF_SECURITY_ADMIN_PASSWORD=homeauto
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - 3000:3000
    volumes:
      - /docker/grafana:/var/lib/grafana/
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    volumes:
      # Mount for influxdb data directory
      - /var/lib/influxdb:/var/lib/influxdb
      # - influxdb_data:/var/lib/influxdb
      # Mount for influxdb configuration
      - /docker/influxdb/config/:/etc/influxdb/
      - /docker/influxdb/types.db:/usr/share/collectd/types.db
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://homeauto.vpn.glasgownet.com:3000"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      # Mount for chronograf database
      - /docker/chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
#    depends_on:
#      - influxdb
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.24.32.13:514"