
# https://github.com/HaoZeke/starDock_compose/blob/master/docker-compose.yml
# https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Traefik_Docker_Compose_Examples
#


include:
  # Just a thought, maybe could have common volumes and networks
  - ../common/volumes.yaml
  - ../common/networks.yaml
  # - ../sonarr/docker-compose.yaml
  # - ../radarr/docker-compose.yaml
  # - ../calibre/docker-compose.yaml
  # - ../nzbget/docker-compose.yaml
  # - ../hydra/docker-compose.yaml
  # - ../music-assistant/docker-compose.yaml
