
# https://github.com/HaoZeke/starDock_compose/blob/master/docker-compose.yml
# https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Traefik_Docker_Compose_Examples
#


include:
  # Just a thought, maybe could have common volumes and networks
  # - ../common-volumes.yaml
  # - ../common-networks.yaml
  - ../sonarr/docker-compose.yaml
  - ../radarr/docker-compose.yaml
  - ../calibre/docker-compose.yaml
  - ../jellyfin/docker-compose.yaml
  - ../nzbget/docker-compose.yaml
  - ../hydra/docker-compose.yaml
  - ../music-assistant/docker-compose.yaml

# services:

#  lidarr:
#    image: linuxserver/lidarr
#    container_name: lidarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - UMASK_SET=022 #optional
#    volumes:
#      - </path/to/appdata/config>:/config
#      - </path/to/music>:/music
#      - </path/to/downloads>:/downloads
#    ports:
#      - 8686:8686
#    restart: unless-stopped

  # immich-server:
  #   container_name: immich_server
  #   image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  #   # extends:
  #   #   file: hwaccel.transcoding.yml
  #   #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
  #   volumes:
  #     # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
  #     - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #     - /etc/localtime:/etc/localtime:ro
  #   env_file:
  #     - immich.env
  #   ports:
  #     - '2283:2283'
  #   depends_on:
  #     - immich-redis
  #     - immich-database
  #   restart: always
  #   healthcheck:
  #     disable: false

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
  #   # Example tag: ${IMMICH_VERSION:-release}-cuda
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   #   file: hwaccel.ml.yml
  #   #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #   volumes:
  #     - model-cache:/cache
  #   env_file:
  #     - immich.env
  #   restart: always
  #   healthcheck:
  #     disable: false

  # immich-redis:
  #   container_name: immich_redis
  #   image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
  #   healthcheck:
  #     test: redis-cli ping || exit 1
  #   restart: always

  # immich-database:
  #   container_name: immich_postgres
  #   image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
  #   env_file:
  #     - immich.env
  #   # environment:
  #   #   POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   #   POSTGRES_USER: ${DB_USERNAME}
  #   #   POSTGRES_DB: ${DB_DATABASE_NAME}
  #   #   POSTGRES_INITDB_ARGS: '--data-checksums'
  #   #   # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
  #   #   # DB_STORAGE_TYPE: 'HDD'
  #   volumes:
  #     # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
  #     - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
  #   restart: always




volumes:
  immich-model-cache:

  downloads_complete:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/"
      device: ":/media/Tank/Downloads/"

  downloads_tmp:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/tmp/"
      device: ":/media/Tank/Downloads/tmp/"

  downloads_intermediate:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/nzbs/intermediate/"
      device: ":/media/Tank/Downloads/nzbs/intermediate/"

  audiobooks:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/Audio Books"
      device: ":/media/Tank/Books/Audio Books/"

  readarr:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/readarr/"

  complete:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/"
      device: ":/media/Tank/Downloads/"

  tv:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/tv/"
      device: ":/media/Tank/TV/"

  movies:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/movies/"
      device: ":/media/Tank/Movies/"

  music:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/media/Tank/Music/"

  podcasts:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/podcasts/"

  music_playlists:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/music_playlists/"

networks:
    traefik_proxy:
      external: true
      name: traefik_traefik_proxy
      # driver: overlay
      # driver: bridge
    # ombi_network:
    #   name: ombi_network
