version: '3.4'

# https://github.com/HaoZeke/starDock_compose/blob/master/docker-compose.yml
# https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Traefik_Docker_Compose_Examples
#

services:

  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:90"
    ports:
      - "90:90"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/www/:/var/www
      - /docker/nginx/logs:/logs
    ports:
      - 88:80
      - 8443:443
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nginx"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix: /test/"
      - "traefik.port=80"
      - "traefik.backend.healthcheck.path=/"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - flame.type=application # "app" works too
      - flame.name=Nginx (88)
      - flame.url=http://viewpoint.house:88

  ## Deploy this later, when ready
  # piwigo:
  #   image: lscr.io/linuxserver/piwigo
  #   container_name: piwigo
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - </path/to/appdata/config>:/config
  #     - </path/to/appdata/gallery>:/gallery
  #   ports:
  #     - 80:80
  #   restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    environment:
      - NZBGET_TRACK=stable
      - PUID=200
      - PGID=200
    ports:
      - 0.0.0.0:6789:6789
    volumes:
      - /docker/nzbget/config:/config
      - /docker/nzbget/data:/downloads
      - /media/store/downloads/nzbs/intermediate:/intermediate
      - /media/store/downloads:/complete
      - /media/store/downloads/tmp:/downloads/tmp
    labels:
      - flame.type=application # "app" works too
      - flame.name=NZBGet
      - flame.url=http://viewpoint.house:6789

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://viewpoint.house:8989"]
      start_period: 60s 
      interval: 30s 
      timeout: 10s
      retries: 5
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix: /sonarr/"
      - "traefik.port=8989"
      - "traefik.backend.healthcheck.path=/"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - flame.type=application # "app" works too
      - flame.name=Sonarr
      - flame.url=http://viewpoint.house:8989
      - flame.icon=television
    environment:
      - PUID=200
      - PGID=200
    ports:
      - 8989:8989
#    expose:
#      - 8989
    volumes:
      - /docker/sonarr/config:/config
      - complete:/complete
      - complete:/downloads/complete
      - tv:/tv
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://viewpoint.house:7878"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix: /radarr/"
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - flame.type=application # "app" works too
      - flame.name=Radarr
      - flame.url=http://viewpoint.house:7878
      - flame.icon=movie-open-outline
    environment:
      - PUID=200
      - PGID=200
    ports:
      - 7878:7878
#    expose:
#      - 7878
    volumes:
      - /docker/radarr/config:/config
      - complete:/complete
      - movies:/movies
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"

  hydra:
    image: linuxserver/hydra:latest
    container_name: hydra
    restart: unless-stopped
    environment:
      - PUID=200
      - PGID=200
    ports:
      - 5075:5075
    healthcheck:
      test: ["CMD", "curl", "-f", "http://viewpoint.house:5075"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - flame.type=application # "app" works too
      - flame.name=Hydra
      - flame.url=http://viewpoint.house:5075
    volumes:
      - /docker/nzbhydra/config:/config
      - /docker/nzbhydra/downloads:/downloads/
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"

#  lidarr:
#    image: linuxserver/lidarr
#    container_name: lidarr
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - UMASK_SET=022 #optional
#    volumes:
#      - </path/to/appdata/config>:/config
#      - </path/to/music>:/music
#      - </path/to/downloads>:/downloads
#    ports:
#      - 8686:8686
#    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    healthcheck:
      test: ["CMD", "curl", "-f", "http://viewpoint.house:5299/home"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - traefik_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lazylibrarian"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix:/lazylibrarian/"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/lazylibrarian"
      - "traefik.port=5299"
      - "traefik.backend.healthcheck.path=/home/"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - flame.type=application # "app" works too
      - flame.name=LazyLibrarian
      - flame.url=http://viewpoint.house:5299
      - flame.icon=book-open-outline
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - /docker/lazylibrarian/config:/config
      - complete:/downloads
      - /media/store/ebooks:/ebooks
      - /media/store/Audio Books:/audiobooks
      - /media/store/home/bagpuss/Arduino_Books:/alternate
    ports:
      - 5299:5299
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    #user: 1000:1000
    network_mode: host
    restart: unless-stopped
    volumes:
      - /docker/jellyfin/config:/config
      - /docker/jellyfin/cache:/cache
      - tv:/media/tv
      - movies:/media/movies
      - music:/media/music
      - /media/store/ebooks:/ebooks
      - /media/store/Audio Books:/audiobooks
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jellyfin"
      - "traefik.frontend.rule=Host:viewpoint.house; PathPrefix:/jellyfin/"
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/jellyfin"
      - "traefik.port=8096"
      - "traefik.backend.healthcheck.path=/system/players"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=viewpoint.house"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - flame.type=application # "app" works too
      - flame.name=Jellyfin
      - flame.url=http://viewpoint.house:8096
      - flame.icon=play-network-outline
    healthcheck:
      test: ["CMD", "apt", "install", "-y", "curl", "curl", "-f", "http://viewpoint.house:8096/web/index.html"]
      start_period: 60s
      interval: 300s
      timeout: 10s
      retries: 5
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.24.32.13:12201"
        tag: "{{.Name}}"

volumes:
  complete:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/downloads/"

  tv:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/tv/"

  movies:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/movies/"

  music:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/music/"

  podcasts:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/podcasts/"

  music_playlists:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/music_playlists/"


networks:
    traefik_proxy:
      driver: bridge
