
# https://github.com/HaoZeke/starDock_compose/blob/master/docker-compose.yml
# https://www.smarthomebeginner.com/traefik-reverse-proxy-tutorial-for-docker/#Traefik_Docker_Compose_Examples
#


include:
  # Just a thought, maybe could have common volumes and networks
  # - ../common-volumes.yaml
  # - ../common-networks.yaml
  - ../sonarr/docker-compose.yaml
  - ../radarr/docker-compose.yaml
  - ../calibre/docker-compose.yaml
  - ../nzbget/docker-compose.yaml
  - ../hydra/docker-compose.yaml
  - ../music-assistant/docker-compose.yaml

volumes:
  downloads_complete:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/"
      device: ":/media/Tank/Downloads/"

  downloads_tmp:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/tmp/"
      device: ":/media/Tank/Downloads/tmp/"

  downloads_intermediate:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/nzbs/intermediate/"
      device: ":/media/Tank/Downloads/nzbs/intermediate/"

  audiobooks:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/Audio Books"
      device: ":/media/Tank/Books/Audio Books/"

  readarr:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/readarr/"

  complete:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/downloads/"
      device: ":/media/Tank/Downloads/"

  tv:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/tv/"
      device: ":/media/Tank/TV/"

  movies:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      # device: ":/srv/nfs4/store/movies/"
      device: ":/media/Tank/Movies/"

  music:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/media/Tank/Music/"

  podcasts:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/podcasts/"

  music_playlists:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/store/music_playlists/"

networks:
    traefik_proxy:
      external: true
      name: traefik_traefik_proxy
      # driver: overlay
      # driver: bridge
    # ombi_network:
    #   name: ombi_network
