---

networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy

volumes:
  actual_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/actual/data/"

services:
  actual_server:
    # https://github.com/actualbudget/actual-server/blob/master/docker-compose.yml
    image: actualbudget/actual-server:latest
    # container_name: actual_server
    # ports:
    #   # This line makes Actual available at port 5006 of the device you run the server on,
    #   # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
    #   - '5006:5006'
    networks:
      - traefik_proxy
    environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - actual-data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.actual.rule=Host(`actual.viewpoint.house`)
      - traefik.http.routers.actual.entrypoints=websecure
      - traefik.http.routers.actual.tls=true
      - traefik.http.routers.actual.tls.certresolver=letsencrypt
      - traefik.http.routers.actual.tls.domains[0].main=actual.viewpoint.house
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=Admin
      - homepage.icon=mdi-cloud-upload-outline
      - homepage.name=Actual
      - homepage.href=https://actual.viewpoint.house
      - homepage.description=Actual Budgeting App