---

networks:
  traefik_proxy:
    external: true
    name: traefik_traefik_proxy
services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 3000:3000
    networks:
      - traefik_proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_traefik_proxy
      - traefik.http.routers.wud-http.entrypoints=web
      - traefik.http.routers.wud-http.rule=Host(`wud.viewpoint.house`)
      - traefik.http.routers.wud-http.middlewares=wud-https
      - traefik.http.middlewares.wud-https.redirectscheme.scheme=https
      - traefik.http.routers.wud.rule=Host(`wud.viewpoint.house`)
      - traefik.http.routers.wud.entrypoints=websecure
      - traefik.http.routers.wud.tls=true
      - traefik.http.routers.wud.tls.certresolver=letsencrypt
      - traefik.http.routers.wud.tls.domains[0].main=wud.viewpoint.house
      - traefik.http.services.wud.loadbalancer.server.port=3000
      - traefik.http.services.wud.loadbalancer.healthcheck.path=/
      - traefik.http.services.wud.loadbalancer.healthcheck.port=3000
