services:
  Watchtower:
    image: v2tec/watchtower:latest
    command: "--label-enable"
    container_name: Watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .watchtower.env
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
