---

networks:
    traefik_proxy:
      external: true
      # Failure to provide the correct external network name results in:
      # Error response from daemon: failed to set up container networking: invalid cluster node while attaching to network
      name: traefik_traefik_proxy

    homeautomation:
      name: homeautomation

# Applications that are included here likely have dependencies on each other
include:
  - ../home-assistant/docker-compose.yaml
  - ../double-take/docker-compose.yaml
  - ../frigate/docker-compose.yaml
  - ../node-red/docker-compose.yaml
  - ../givtcp/docker-compose.yaml
  - ../esphome/docker-compose.yaml
  - ../zigbee2mqtt/docker-compose.yaml
  - ../eclipse-mosquitto/docker-compose.yaml
  - ../matter-server/docker-compose.yaml
  - ../predbat/docker-compose.yaml
