---

# traefik_proxy and homeautomation are created by ../network-stack and consumed here
# as external via ../common/networks.yaml.
# Applications that are included here likely have dependencies on each other
include:
  - ../common/networks.yaml
  - ../home-assistant/docker-compose.yaml
  - ../double-take/docker-compose.yaml
  - ../frigate/docker-compose.yaml
  - ../node-red/docker-compose.yaml
  - ../givtcp/docker-compose.yaml
  - ../esphome/docker-compose.yaml
  - ../zigbee2mqtt/docker-compose.yaml
  - ../eclipse-mosquitto/docker-compose.yaml
  - ../matter-server/docker-compose.yaml
  - ../predbat/docker-compose.yaml
