# networks:
#   traefik_proxy:
#     external: true
#     name: traefik_traefik_proxy
#   homeautomation:
#     external: true

volumes:
  double_take_storage:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.24.32.5,rw
      device: ":/srv/nfs4/docker_nfs/double_take/storage/"

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take:1.13.2
    networks:
      - traefik_proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      start_period: 15s
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - eclipse-mosquitto
      - frigate
    volumes:
      - double_take_storage:/.storage
    labels:
      - traefik.enable=true
      - traefik.http.routers.double-take.rule=Host(`double-take.viewpoint.house`)
      - traefik.http.routers.double-take.entrypoints=websecure
      - traefik.http.routers.double-take.tls=true
      - traefik.http.routers.double-take.tls.certresolver=letsencrypt
      - traefik.http.routers.double-take.tls.domains=double-take.viewpoint.house
      - traefik.http.services.double-take.loadbalancer.server.port=3000
      - traefik.http.services.double-take.loadbalancer.healthcheck.path=/
      - traefik.http.services.double-take.loadbalancer.healthcheck.port=3000
      - homepage.group=Home Automation
      - homepage.icon=mdi-tag-faces
      - homepage.name=Double-Take
      - homepage.href=https://double-take.viewpoint.house
      - homepage.description=Facial Recognition Service
      - com.centurylinklabs.watchtower.enable=true
    logging:
      driver: gelf
      options:
        gelf-address: "udp://72.24.32.13:12201"
        tag: "{{.Name}}"
